# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: searchstar
subtitle: ''
description: ''
keywords:
author: searchstar
language: zh-Hans
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://seekstar.github.io/
permalink: :year/:month/:day/:post_title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: googleca342d2ad36b95d9.html

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true

syntax_highlighter: # empty

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: tree

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: 'git'
  repository:
    github: git@github.com:seekstar/seekstar.github.io.git,master
    #blog.seekstar.top: blog:~/searchstar-blog.git

mathjax:
  every_page: true

pandoc:
  # extensions:
  #   - +angle_brackets_escapable
  #   - +pipe_tables
  #   - -ascii_identifiers
  #   - +strikeout+emoji
  #   - +shortcut_reference_links
  args: [
    '--preserve-tabs',
    # I don't know why but mathjax won't work without hexo-filter-mathjax or --mathjax
    '--mathjax',
    # -smart: 不把引号渲染成带方向的引号。
    # +backtick_code_blocks: 代码块
    # -implicit_figures: 防止在图片后面将方括号里的东西作为caption。<https://github.com/wzpan/hexo-renderer-pandoc/issues/34>
    # +gfm_auto_identifiers: 用github的方式生成header之类的identifier
    # +intraword_underscores: 不把下划线用来强调。强调用星号。
    # +hard_line_breaks: 两行之间就算没有额外的空行也显示成两行，而不是像Latex那样显示成一行。
    # +autolink_bare_uris: Makes all absolute URIs into links, even when not surrounded by pointy braces <...>
    '--from', 'markdown-smart+backtick_code_blocks-implicit_figures+gfm_auto_identifiers+intraword_underscores+hard_line_breaks+autolink_bare_uris',
    '--filter', './node_modules/hexo-pandoc-header-anchor/header-anchor.py',
  ]
